include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 3000

build-review:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    DOCKER_BUILD_ARG_DEBUG: "debug"
    DOCKER_BUILD_ARG_OPEN_CITY_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
    DOCKER_BUILD_ARG_BERTH_RESERVATIONS_API_URL: "https://venepaikka-api.test.hel.ninja/graphql_v2/"
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
    DOCKER_BUILD_ARG_DEBUG: "debug"
    DOCKER_BUILD_ARG_OPEN_CITY_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
    DOCKER_BUILD_ARG_BERTH_RESERVATIONS_API_URL: "https://venepaikka-api.test.hel.ninja/graphql_v2/"
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
    DOCKER_BUILD_ARG_OPEN_CITY_PROFILE_API_URL: "https://api.hel.fi/profiili/"
    DOCKER_BUILD_ARG_BERTH_RESERVATIONS_API_URL: "https://api.hel.fi/berths/"
  only:
    refs:
      - master
      # this regexp will match release-tags
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    POSTGRES_ENABLED: 0

# This will enable staging ci-pipeline
staging:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
