version: '3.7'
services:
    app:
        build:
            context: .
            target: ${DOCKER_TARGET:-development}
        env_file: docker-compose.env.yaml
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3333:3000"
        container_name: berth-federation

networks:
    default:
        name: helsinki
